spring:
  datasource:
    url: jdbc:mariadb://ant-hit.cy8zp3fimxzo.ap-northeast-2.rds.amazonaws.com/FSSWTest
    username: anthit
    password: ahwlfdlemf!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace